name: Artifact Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: hello.txt

  download:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: hello-artifact
        path: ./artifacts

    - name: Display the content of hello.txt
      run: cat ./artifacts/hello.txt
